language: node_js

services:
  - docker

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend

after_success:
  - docker tag udagram-api-feed nerojz/udagram-api-feed
  - docker tag udagram-api-user nerojz/udagram-api-user
  - docker tag reverseproxy nerojz/reverseproxy
  - docker tag udagram-frontend nerojz/udagram-frontend
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push nerojz/udagram-api-feed:v1
  - docker push nerojz/udagram-api-user:v1
  - docker push nerojz/reverseproxy:v1
  - docker push nerojz/udagram-frontend:v1